/*
 * This file is a product of Sun Microsystems, Inc. and is provided for
 * unrestricted use provided that this legend is included on all tape
 * media and as a part of the software program in whole or part.  Users
 * may copy or modify this file without charge, but are not authorized to
 * license or distribute it to anyone else except as part of a product
 * or program developed by the user.
 *
 * THIS FILE IS PROVIDED AS IS WITH NO WARRANTIES OF ANY KIND INCLUDING THE
 * WARRANTIES OF DESIGN, MERCHANTIBILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE, OR ARISING FROM A COURSE OF DEALING, USAGE OR TRADE PRACTICE.
 *
 * This file is provided with no support and without any obligation on the
 * part of Sun Microsystems, Inc. to assist in its use, correction,
 * modification or enhancement.
 *
 * SUN MICROSYSTEMS, INC. SHALL HAVE NO LIABILITY WITH RESPECT TO THE
 * INFRINGEMENT OF COPYRIGHTS, TRADE SECRETS OR ANY PATENTS BY THIS FILE
 * OR ANY PART THEREOF.
 *
 * In no event will Sun Microsystems, Inc. be liable for any lost revenue
 * or profits or other special, indirect and consequential damages, even
 * if Sun has been advised of the possibility of such damages.
 *
 * Sun Microsystems, Inc.
 * 2550 Garcia Avenue
 * Mountain View, California  94043
 */

#ifndef	gcc_HEADER
#define	gcc_HEADER

/*
 * gcc_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `gcc.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	gccwin;
	Xv_opaque	controls;
	Xv_opaque	color_list;
	Xv_opaque	color_blot;
	Xv_opaque	color_name;
	Xv_opaque	group1;
	Xv_opaque	group3;
	Xv_opaque	apply;
	Xv_opaque	reset;
	Xv_opaque	group2;
	Xv_opaque	group4;
} gcc_gccwin_objects;

extern gcc_gccwin_objects	*gcc_gccwin_objects_initialize();

extern Xv_opaque	gcc_gccwin_gccwin_create();
extern Xv_opaque	gcc_gccwin_controls_create();
extern Xv_opaque	gcc_gccwin_color_list_create();
extern Xv_opaque	gcc_gccwin_color_blot_create();
extern Xv_opaque	gcc_gccwin_color_name_create();
extern Xv_opaque	gcc_gccwin_group1_create();
extern Xv_opaque	gcc_gccwin_group3_create();
extern Xv_opaque	gcc_gccwin_apply_create();
extern Xv_opaque	gcc_gccwin_reset_create();
extern Xv_opaque	gcc_gccwin_group2_create();
extern Xv_opaque	gcc_gccwin_group4_create();
#endif
