# 
#    SCCS ID: %Z%%M% %I% %E% SMI
#
#    Copyright (c) 1992 Sun Microsystems, Inc.  All rights reserved.
#    See LEGAL_NOTICE file for terms of the license. 
# 

choosers:
	make -f Makefile.cs
	make -f Makefile.ccb
	make -f Makefile.fcb
	make -f Makefile.driver

choosers_svr4:
	make -f Makefile.cs.svr4
	make -f Makefile.ccb.svr4
	make -f Makefile.fcb.svr4
	make -f Makefile.driver.svr4

delete:
	make -i -f Makefile.cs delete
	make -i -f Makefile.ccb delete
	make -i -f Makefile.fcb delete
	make -i -f Makefile.driver delete
