#
#    SCCS ID: %Z%%M% %I% %E% SMI
#
#    Copyright (c) 1992 Sun Microsystems, Inc.  All rights reserved.
#    See LEGAL_NOTICE file for terms of the license.
#

all: ColorChooserButton.o

ColorChooserButton.o: ColorChooserButton.cc ColorChooserButton.h
	CC -c ColorChooserButton.cc \
	      -I. -I$(OPENWINHOME)/include -I$(UITHOME)/include/c++

delete:
	/bin/rm -f *.o core
