/*
 * entries_stubs.cc - Notify and event callback function stubs.
 * This file was generated by `guic' from `entries.G'.
 */

#include "Button.h"
#include "ListChoice.h"

/*
 * Notify callback function for `add_button'.
 */
void add_button_handler (UIObject *object)
{
  fputs ("entries: add_button_handler\n", stderr);

  /* guic_start_connections DO NOT EDIT THIS SECTION */

  /* guic_end_connections */

  return;
}

/*
 * Notify callback function for `entry_list'.
 */
void entry_list_handler (UIObject *object)
{
  char *value;

  value = object->getValue (value);

  switch (((ListChoice *) object)->getOperation ()) {
  case DESELECT:
    fprintf (stderr, "entries: entry_list_handler: DESELECT: %s\n", value);
    break;

  case SELECT:
    fprintf (stderr, "entries: entry_list_handler: SELECT: %s\n", value);
    break;

  case VALIDATE:
    fprintf (stderr, "entries: entry_list_handler: VALIDATE: %s\n", value);
    break;

  case DELETE:
    fprintf (stderr, "entries: entry_list_handler: DELETE: %s\n", value);
    break;

  case UNKNOWN:
  default:
    break;
  }

  /* guic_start_connections DO NOT EDIT THIS SECTION */

  /* guic_end_connections */

  delete value;
  return;
}

/*
 * Notify callback function for `delete_button'.
 */
void delete_button_handler (UIObject *object)
{
  fputs ("entries: delete_button_handler\n", stderr);

  /* guic_start_connections DO NOT EDIT THIS SECTION */

  /* guic_end_connections */

  return;
}
