#
#    SCCS ID: %Z%%M% %I% %E% SMI
#
#    Copyright (c) 1990-1992 Sun Microsystems, Inc.  All rights reserved.
#    See LEGAL_NOTICE file for terms of the license.
#
examples:
	cd ColorMaps/Display; make
	cd ColorMaps/Worms; make
#	cd DragAndDrop/Canvas; make
#	cd DragAndDrop/Panel; make
#	cd DragAndDrop/PrintTool; make
#	cd HotRegions/Canvas/PostScript; make
	cd HotRegions/Canvas/Xlib; make
	cd HotRegions/Panel; make
	cd Images/Choice; make
	cd Images/List; make
	cd Menus; make
	cd NewUITClasses/PropertiesWindow; make
#	cd NewUITClasses/Choosers; make choosers
	cd NotifyTargets; make
#	cd PostScript/Circles; make
#	cd PostScript/ImageButton; make
	cd Windows; make
	cd SlingShot; make ss_examples

clean:
	cd ColorMaps/Display; make -i clean
	cd ColorMaps/Worms; make -i clean
	cd DragAndDrop/Canvas; make -i clean
	cd DragAndDrop/Panel; make -i clean
	cd DragAndDrop/PrintTool; make -i clean
	cd HotRegions/Canvas/PostScript; make -i clean
	cd HotRegions/Canvas/Xlib; make -i clean
	cd HotRegions/Panel; make -i clean
	cd Images/Choice; make -i clean
	cd Images/List; make -i clean
	cd Menus; make -i clean
	cd NewUITClasses/PropertiesWindow; make -i clean
	cd NewUITClasses/Choosers; make -i clean
	cd NotifyTargets; make -i clean
	cd PostScript/Circles; make -i clean
	cd PostScript/ImageButton; make -i clean
	cd Windows; make -i clean
	cd SlingShot; make clean
