#
#    SCCS ID: %Z%%M% %I% %E% SMI
#
#    Copyright (c) 1990-1992 Sun Microsystems, Inc.  All rights reserved.
#    See LEGAL_NOTICE file for terms of the license.
#
ss_examples:
	cd CSArrayTile; make
	cd CSDrawImage; make
	cd CSDrawText; make

clean:
	cd CSArrayTile; make clean
	cd CSDrawImage; make clean
	cd CSDrawText; make clean
